content/urls.py
from django.urls import path

from content import views
app_name = 'Content'
urlpatterns = [
    path("make/", views.con_making, name="content_make"),
    path("page/<int:content_number>/", views.con_page, name='content_detail'),
    path("reserve<int:content_number>/", views.reserve, name='reserve'),
    path("pay_page", views.pay_page, name='pay_page'),
]

faq/urls.py
from django.urls import path

from faq import views

urlpatterns = [
    path("faq_question/", views.faq_question, name='faq_question'),
    path("faq_answer/", views.faq_answer, name='faq_answer'),
]

ggaggoong/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import user.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user.views.home, name='home'),
    path('/', include('user.urls')),
    path('content/', include('content.urls')),
    path('faq/', include('faq.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/models.py
from django.db import models
from user.models import User, Host

# Create your models here.
class Contents(models.Model):
    title_img = models.ImageField(
        upload_to="content/image/",
        blank=True,
        null=True
    )
    title_name = models.CharField(max_length=100)
    sub_title_name = models.CharField(max_length=100)
    content_date = models.DateTimeField()
    duration = models.IntegerField()
    location = models.CharField(max_length=100)
    people_number = models.IntegerField()
    age_min = models.IntegerField()
    age_max = models.IntegerField()
    price = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    host_id = models.ForeignKey(Host, on_delete=models.CASCADE, null=True)

class Contents_Detail(models.Model):
    detail = models.CharField(max_length=500)
    detail_img = models.ImageField(
        upload_to="content/detail_image/",
        blank=True,
        null=True
    )
    contents_id = models.ForeignKey('Contents', on_delete=models.CASCADE, null=True)
    host_id = models.ForeignKey(Host, on_delete=models.CASCADE, null=True)


class Reserve(models.Model):
    content_id = models.ForeignKey(Contents, on_delete=models.PROTECT)
    reserve_user = models.ForeignKey(User, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    reserve_alive = models.BooleanField(default=True)
    canceled_at = models.DateTimeField(null=True)

content/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseBadRequest, JsonResponse
from content.models import Contents, Contents_Detail
from faq.models import FAQ, FAQ_Answer
from content.models import Reserve
from user.models import User, Host
from django.contrib             import messages
import json
from collections import defaultdict

detail_count = {
    "count": 0,
}
def pay_page(request):
    return render(request,'content/pay_page.html')

def reserve(request, content_number):
    tmp_reserve = Reserve.objects.filter(content_id=content_number, reserve_alive=True)
    content = Contents.objects.get(id=content_number)
    if len(tmp_reserve) > content.people_number:
        print('more than the number')
        messages.warning(request, "more than the number")
        return redirect(f'/content/page/{content_number}', content_number)
    else:
        print('else')
        reserve = Reserve()
        reserve.content_id = content
        reserve.reserve_user = User.objects.get(id=request.user.id)
        reserve.save()
        print(reserve)
    reserves = Reserve.objects.filter(content_id=content_number)
    return render(request, 'content/pay_page.html', {'reserves':reserves, 'content':content})

def con_making(request):

    context = {

         }       
    if_check_detail_img = []
    if_check_detail = []
    if request.method == "POST":
        # request_body = json.loads(request.body)
        for i in range(int(request.POST.get("detail_count"))):
            if_check_detail_img.append(request.FILES.get(f"detail_img_{i}"))
            if_check_detail.append(request.POST.get(f"detail_{i}"))

        if (
                request.POST.get("title_name") and
                request.POST.get("sub_title_name") and
                request.FILES.get("title_image") and
                request.POST.get("content_date") and
                request.POST.get("duration") and
                request.POST.get("location") and
                request.POST.get("people_number") and
                request.POST.get("age_min") and
                request.POST.get("age_max") and
                request.POST.get("price") and
                len(if_check_detail) == int(request.POST.get("detail_count")) and
                len(if_check_detail_img) == int(request.POST.get("detail_count"))
        ):
            process = True
        else:
            process = False

        for i in range(int(request.POST.get("detail_count"))):
            if(
                    request.FILES.get(f"detail_img_{i}") and
                    request.POST.get(f"detail_{i}")
            ):
                process = True
            else:
                process = False

        if process:
            new_content = Contents()
            new_content.title_name = request.POST.get("title_name")
            new_content.sub_title_name = request.POST.get("sub_title_name")
            new_content.title_img = request.FILES.get("title_image")
            new_content.content_date = request.POST.get("content_date")
            new_content.duration = request.POST.get("duration")
            new_content.location = request.POST.get("location")
            new_content.people_number = request.POST.get("people_number")
            new_content.age_min = request.POST.get("age_min")
            new_content.age_max = request.POST.get("age_max")
            new_content.price = request.POST.get("price")
            new_content.host_id = Host.objects.get(user_id=request.user.id)
            new_content.save()

            id_number = new_content
            content_number = new_content.id
            try:
                for j in range(int(request.POST.get("detail_count"))):
                    new_detail_content = Contents_Detail()
                    new_detail_content.contents_id = id_number
                    new_detail_content.detail = request.POST.get(f"detail_{j}")
                    new_detail_content.detail_img = request.FILES.get(f"detail_img_{j}")
                    new_detail_content.host_id = Host.objects.get(user_id=request.user.id)
                    new_detail_content.save()
            except:
                print('detail fail')

            print('contetnt number : ', content_number)
            print(new_detail_content)
            return redirect(f'/content/page/{content_number}', content_number)
        else:
            context["error"] = "정확히 모두 입력바랍니다."
            return JsonResponse(context, status=400)

    return render(request, "content/content_making.html", context)


def con_page(request, content_number):
    new_content = Contents.objects.get(id=content_number)
    # print(new_content.title_name)
    reserves = Reserve.objects.filter(content_id=content_number, reserve_alive=True)
    # print(len(reserves))
    faq = FAQ.objects.filter(faq_content=content_number).order_by('-created_at')
    # faq_id = FAQ.objects.filter(faq_content=content_number).values_list('id', flat=True)
    # faq_answers = FAQ_Answer.objects.filter(question_id__in=faq_id).order_by('-created_at')
    faq_answers = FAQ_Answer.objects.filter(question_id__in=faq).order_by('-created_at')
    # faq_answers = []
    faq_list = []
    # print('afdssdfasd')
    for faq_question in faq:
        # faq_answers.append(faq_question.answer.order_by('-created_at')[0])

        faq_list.append([faq_question,])
    for idx, fa in enumerate(faq_list):
        for ans in faq_answers:
            if ans.question_id == fa[0]:
                faq_list[idx] = [fa[0],ans]
    
    # print(faq_list)

    # 결제하기 버튼 clickable flag 값 생성해야함 
    reserve_available = False
    host_flag = False
    reserve_flag = Reserve.objects.filter(content_id=content_number, reserve_user=request.user.id)
    if reserve_flag:
        reserve_available = False
    else:
        reserve_available = True
    if new_content.host_id.id == request.user.id:
        host_flag = True
    else:
        host_flag = False
    # print('new_content.host_id : ', new_content.host_id.id)
    # print('request.user.id : ', request.user.id)
    context = {
        "new_content": new_content,
        "new_detail_content": [],
        "faqs" : faq,
        "faq_len" : len(faq),
        "reserves_len" : len(reserves),
        "faq_answers" : faq_answers,
        "faq_list" : faq_list,
        "reserve_available" : reserve_available,
        "host_flag" : host_flag,
    }
    for item in Contents_Detail.objects.filter(contents_id=content_number):
        context["new_detail_content"].append(item)

    return render(request, "content/content_page.html", context)

content/templates/content/content_making.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

  <body class="bg-light">

<div class="container" >
  <main>
    <div class="py-5 text-center">
      <h2>어떤 놀이인가요?</h2>
      <p class="lead">어떤 놀이인지 자세히 알려주세요. </p>
    </div>

    <form action="/content/make/" method="post" id="content-make" enctype="multipart/form-data">
        {% csrf_token %}
    <div class="row g-5">
      <!-- <div class="col-md-7 col-lg-8"> -->
        <!-- <h4 class="py-5 text-center">어떤 놀이인가요?</h4> -->
        <form class="needs-validation" novalidate>
          <div class="row g-3">
            <div class="col-12">
              <label for="firstName" class="form-label">콘텐츠 제목을 입력해 주세요</label>
              <input type="text" class="form-control" name="title_name" id="title_name" placeholder="" value="" required>
              <div class="invalid-feedback">
                콘텐츠 제목을 입력해 주세요.
              </div>
            </div>

            <div class="col-12">
              <label for="lastName" class="form-label">콘텐츠 소제목을 입력해 주세요</label>
              <textarea type="text" rows='3' class="form-control" name="sub_title_name" id="sub_title_name" placeholder="" value="" required></textarea>
              <div class="invalid-feedback">
                콘텐츠 소제목을 입력해 주세요.
              </div>
            </div>

            <div class="col-12">
              <label for="username" class="form-label">타이틀 이미지를 올려 주세요</label>
              <div class="input-group has-validation">
                <input type="file" name="title_image" id="title_image"  class="form-control" placeholder="Username" required>
              <div class="invalid-feedback">
                타이틀 이미지를 올려 주세요.
                </div>
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">콘텐츠 진행 날짜와 시간을 입력해 주세요 <span class="text-muted">(Optional)</span></label>
              <input type="datetime-local" name="content_date" id="content_date" class="form-control">
              <div class="invalid-feedback">
                콘텐츠 진행 날짜와 시간을 입력해 주세요.
              </div>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">콘텐츠를 몇시간동안 진행하는지 입력해 주세요</label>
              <input type="number" name="duration" id="duration" class="form-control" placeholder="1" required>
              <div class="invalid-feedback">
                콘텐츠를 몇시간동안 진행하는지 입력해 주세요.
              </div>
            </div>

            <div class="col-12">
              <label for="address2" class="form-label">콘텐츠 진행 장소를 입력해 주세요</label>
              <input type="text" name="location" id="location" class="form-control" placeholder="강남구 도곡동" required>
              <div class="invalid-feedback">
                콘텐츠 진행 장소를 입력해 주세요.
              </div>
            </div>

            <div class="col-12">
                <label for="address2" class="form-label">콘텐츠 참가 인원 수를 입력해주세요</label>
                <input type="number" name="people_number" id="people_number" class="form-control" placeholder="3" required>
                <div class="invalid-feedback">
                    콘텐츠 참가 인원 수를 입력해주세요.
                </div>
            </div>
            <div>
                <label for="address2" class="form-label">콘텐츠 참가 가능한 아이의 나이를 입력해주세요</label>
                <div class="col-md-4">
                    최소나이(개월 수)
                    <input type="number" name="age_min" id="age_min" class="form-control" placeholder="20" required>
                </div>
                <div class="col-md-4">
                    최대나이(개월 수)
                    <input type="number" name="age_max" id="age_max" class="form-control" placeholder="40" required>
                </div>


                <div class="invalid-feedback">
                    콘텐츠 참가 가능한 아이의 나이를 입력해주세요.
                </div>
            </div>
            <div class="col-4">
                콘텐츠 가격을 입력해 주세요(단위 : 원)
                <input type="number" name="price" id="price" class="form-control" placeholder="30000" required>
            </div>
            <div id = "detail_text" form = "content-make">
            </div>

            <div class="btn btn-outline-success" onclick="count_up()">추가하기 버튼</div>
            <div class="btn btn-outline-danger" onclick="count_down()">삭제하기 버튼</div>


        </form>

          <hr class="my-4">

          <button class="w-100 btn btn-primary btn-lg" type="button" onclick="sendData()">놀이 만들기!</button>
        </form>
      <!-- </div> -->
    </div>
  </main>


</div>



  </body>



    <script>
        let detail_num = 0
        function count_up(){
            if (detail_num <= 10){
                let con_add = `
                <div id="${detail_num}">
                    <div class="col-12" >
                        <label for="username" class="form-label"> ${detail_num +1} 번째 상세 이미지 추가하기</label>
                        <div class="input-group has-validation">
                            <input type='file' name='detail_img_${detail_num}' id="detail_img_${detail_num}"  class="form-control" required>
                        </div>
                    </div>
                    <div class="col-12">
                        <label for="lastName" class="form-label"> ${detail_num +1} 번째 상세 설명을 입력해 주세요</label>
                        <textarea class='form-control input-lg' rows='3' type='text' name='detail_${detail_num}' id="detail_${detail_num}" placeholder="" value="" required></textarea>
                        <div class="invalid-feedback">
                            상세 설명을 입력해 주세요.
                        </div>
                    </div>
                </div>`;


                $("#detail_text").append(con_add);
                detail_num = detail_num + 1;
            }


        }

        function count_down(){
            if (detail_num > 0){

                detail_num = detail_num - 1;
                $(`#${detail_num}`).remove();
            }
        }
        function getCsrfToken(){
            return document.cookie
                .split(';')
                .find((item) => item.includes('csrftoken'))
                .split('=')[1];
        }

        async function sendData(){
            const detailLength = detail_num;
            const detailList = [];

            const bodyForm = new FormData();
            // add other elements
            bodyForm.append("detail_count", detailLength)
            bodyForm.append("title_name", document.querySelector(`input#title_name`).value)
            bodyForm.append("sub_title_name", document.querySelector(`textarea#sub_title_name`).value)
            bodyForm.append("title_image", document.querySelector(`input#title_image`).files[0])
            bodyForm.append("content_date", document.querySelector(`input#content_date`).value)
            bodyForm.append("duration", document.querySelector(`input#duration`).value)
            bodyForm.append("location", document.querySelector(`input#location`).value)
            bodyForm.append("people_number", document.querySelector(`input#people_number`).value)
            bodyForm.append("age_min", document.querySelector(`input#age_min`).value)
            bodyForm.append("age_max", document.querySelector(`input#age_max`).value)
            bodyForm.append("price", document.querySelector(`input#price`).value)


            for (let i = 0; i < detailLength; i++) {
                bodyForm.append(`detail_${i}`, document.querySelector(`textarea#detail_${i}`).value);
                bodyForm.append(`detail_img_${i}`, document.querySelector(`input#detail_img_${i}`).files[0]);
            }

            let response = await fetch("/content/make/", {
                method: "POST",
                headers: {
                    // "Content-Type": "multipart/form-data",
                    "X-CSRFToken": getCsrfToken(),
                },
                body: bodyForm,
            });

            if(response.ok) {
                await alert("성공");
                window.location.href = response.url;
            } else {
                let responseBody = await response.json()
                alert(responseBody["error"]);
            }
        }

    </script>


</body>
{% endblock %} 

content/templates/content/content_page.html
{% extends "base.html" %}

 {% block title %}content-page{% endblock %}

    {% block head %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    {% endblock %}

  {% block content %}
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message.message }}
            <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
    {% endif %}


<br/>
<br/>
<div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-7" style="">
                        {% if new_content.title_img %}
                            <img class="card-img-top mb-5 mb-md-0" src="{{ new_content.title_img.url }}" style="border: 3px ridge grey; height: 20rem; object-fit: scale-down;" alt="...">
                        {% endif %}
                    </div>
                    <div class="col-md-5">

                        <h3 class="display-5 fw-bolder">{{ new_content.title_name }}</h3>
                        <div class="fs-5 mb-3">
                            <h4>{{ new_content.sub_title_name }}</h4>
                        </div>

                        <div class ="detail"> <a style="color:gray">진행일자</a>  : {{ new_content.content_date|date:" Y M d일 D" }} </div>
                        <div class ="detail"> <a style="color:gray">진행 시간</a> : {{ new_content.duration }} </div>
                        <div class ="detail"> <a style="color:gray">장소</a>     : {{ new_content.location }} </div>
                        <div class ="detail"> <a style="color:gray">인원</a>     : {{ new_content.people_number }} </div>
                        <div class ="detail"> <a style="color:gray">나이</a>     : {{ new_content.age_min }} ~ {{ new_content.age_max }} </div>
                        <div class ="detail"> <a style="color:gray">가격</a>     : {{ new_content.price }} </div>


<!--                            <div class="d-flex">-->

                                {% if host_flag %}
                                    <h3>호스트 입니다 </h3>
                                {% else %}
                                {% if reserves_len >= new_content.people_number %}
                                가득참
                                {% else %}
                                <div> 예약현황 : {{reserves_len}}  / {{new_content.people_number}} </div>

                                {% if reserve_available %}

                              <div>
                                  <a href="{% url 'Content:reserve' new_content.id %}"><button style="margin-top: 10px;" class="btn btn-outline-dark flex-shrink-0 reserve" type="button" name="action">결제하기</button></a>
                              </div>

                                {% else %}
                                <h3>이미 결제함 </h3>
                                {% endif %}
                                {% endif %}
                                {% endif %}
                            </div>
                    </div>
                </div>

<hr/>

    <h3> 상세 설명</h3>
<br/>
<br/>
<div >

    {% for item in new_detail_content %}
    {% if item.detail_img %}
    <div style ="text-align : center;">
        <img src="{{ item.detail_img.url }}" style="width:50%" />
    </div>
    <br/>
    {% endif %}

    <br/>
    <div style ="text-align : center;"> {{ item.detail }} </div>
    {% endfor %}
    <br/>
    <br/>
</div>


    
<br/>
<br/>
<!--{% if host_flag %}-->

<!--    <h3>호스트 입니다 </h3>-->
<!--{% else %}-->
<!--{% if reserves_len >= new_content.people_number %}-->
<!--가득참-->
<!--{% else %}-->
<!--{{reserves_len}}-->
<!--{{new_content.people_number}}-->
<!--{% if reserve_available %}-->
<!--<a href="{% url 'Content:reserve' new_content.id %}"><button class="button waves-effect waves-light" name="action">결제하기</button></a>-->
<!--{% else %}-->
<!--<h3>이미 결제함 </h3>-->
<!--{% endif %}-->
<!--{% endif %}-->
<!--{% endif %}-->


<hr/>
<h3>문의하기</h3>

<div>

    <table border='1' class='faqTable table table-hover text-center'>
        <tr>
            <td>번호</td>
            <td>질문</td>
            <td>작성자</td>
            <td>작성일</td>
        </tr>
        <tbody class="faqTbody">
            {% for faq in faq_list %}
            <tr id="tr_{{ forloop.revcounter }}">
                <td>{{ forloop.revcounter }}</td>
                <td>{{ faq.0.question }}</td>
                <td>{{ faq.0.questioner }}</td>
                <td>{{ faq.0.created_at }}</td>
                <td id = "faq.0.id"><button id="{{ forloop.revcounter }}" onclick="faq_answer(this.id, {{ faq.0.id }})" class="btnAnswer">답변하기</button></td>
            </tr>
            {% if faq.1 %}
            <tr>
                <td>답변</td>
                <td>{{faq.1.answer}}</td>
                <td>주인장</td>
                <td>{{faq.1.created_at}}</td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
        
    </table>

</div>

<div class="input-group">
  <span class="input-group-text">문의하기</span>
  <textarea class=" faqQuestion form-control " aria-label="With textarea"></textarea>



<!--    <textarea class='faqQuestion' placeholder="문의"></textarea>-->
    <input type="button" class="btnSend" value="전송">
</div>

<br>




<script>
    let btnSend = document.querySelector('.btnSend');


    btnSend.addEventListener('click', e=>{
        console.log('btn')
        let content = document.querySelector('.faqQuestion').value;

        let param ={
            'question' : content,
            'faq_content' : '{{new_content.id}}',
            'questioner' : '{{ user.id }}',
        }

        $.ajax({
            url : '{% url 'faq_question' %}',
            type: 'POST',
            headers: {
                'X-CSRFTOKEN' : "{{ csrf_token }}",
            },
            data : JSON.stringify(param),
            success:function(data){
                console.log(data);

                let faqTable = document.querySelector('.faqTbody');
                let newTr = document.createElement('tr');
                let str = `
                    <td>${ data.question }</td>
                    <td>${ data.questioner }</td>
                    <td>${ data.created_t }</td>
                    `;
                newTr.innerHTML = str;
                faqTable.prepend(newTr);

            },
            error: function(){
                alert('문의 남기기에 에러남');
            }
        
        })
        $('.faqQuestion').val('');
        window.location.reload()



    })
    let target_question_id
    var _real_id
    function faq_answer(reply_id, real_id){
        console.log(reply_id);
        target_question_id = reply_id;
        let faq_question = document.querySelector('#tr_'+target_question_id);
        console.log(faq_question)
        let tmp_tr = document.createElement('tr');
        let ass = `
            <td></td>
            <td colspan="3"><textarea style="width:100%"" class='faqAnswer' placeholder="답변하기"></textarea></td>
            <td><input type="button" class="faqAnswerSend" value="전송"></td>
            `;
        tmp_tr.innerHTML = ass;
        faq_question.after(tmp_tr);
        _real_id = real_id
        console.log(ass)
        console.log(real_id)
    };

    

    $('.faqAnswerSend').live('click', '.dynamicElement', function(){
        console.log('asdfasdfasd');
        console.log(_real_id)
        let content = document.querySelector('.faqAnswer').value;
        let faq_id = document.querySelector('.button');
        console.log(faq_id)
        console.log(content)
        let param ={
            'answer' : content,
            'question_id' : _real_id,
            'answerer' : '{{ user.id }}',
        }
        $.ajax({
            url : '{% url 'faq_answer' %}',
            type: 'POST',
            headers: {
                'X-CSRFTOKEN' : "{{ csrf_token }}",
            },
            data : JSON.stringify(param),
            success:function(data){
                console.log('ssibval');
                console.log(data);
                console.log(target_question_id);

                // let faq_question = document.querySelector('#tr_'+target_question_id);
                // console.log(faq_question)
                // let tmp_tr = document.createElement('tr');
                // let ass = `
                //     <td>${ data.answer }</td>
                //     <td>${ data.answerer }</td>
                //     <td>${ data.created_at }</td>
                //     `;
                // tmp_tr.innerHTML = ass;
                // faq_question.after(tmp_tr);

            },
            error: function(){
                alert('답변 남기기에 에러남');
            }
        
        })
        // to-do : erase tr tags
        window.location.reload()
    });


    

</script>

<br/>
<br/>

{% endblock %}

content/templates/content/pay_page.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}
{% block content %}


<body class="main-bg" style="background-image: url({% static 'baby_bck.jpeg' %}); background-position: center; background-repeat: no-repeat; background-size: cover;">

    <!-- Custom styles for this template -->
    <link href="carousel.css" rel="stylesheet">
  </head>

<body style="height: 80rem; display: inline-block;">
    <div class="super_pay">
      <div class="inner_pay">
        죄송합니다 <br>
      아직 결제 서비스가 이루어지지 않고 있습니다<br>
      예약과 관련해서는 <br>
      저희에게 이메일로 문의 주시면 감사합니다
      <br>
      이용에 불편을 드려 죄송합니다<br>
      </div>
      
    </div>

    
</body>
</html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>


<style>

  .super_pay{
    text-align: center;
    height: 45rem;
    font-size: 3rem;
    font-weight: 100;
    padding-top: 10rem;
  }
  .inner_pay{
    text-align: center;
    background-color: rgba(253, 244, 215, 0.9);
    width: 55rem;
    margin-left: 20rem;
  }
</style>


{% endblock %} 