content/urls.py
from django.urls import path

from content import views
app_name = 'Content'
urlpatterns = [
    path("make/", views.con_making, name="content_make"),
    path("page/<int:content_number>/", views.con_page, name='content_detail'),
    path("reserve<int:content_number>/", views.reserve, name='reserve'),
    path("pay_page", views.pay_page, name='pay_page'),
]

faq/urls.py
from django.urls import path

from faq import views

urlpatterns = [
    path("faq_question/", views.faq_question, name='faq_question'),
    path("faq_answer/", views.faq_answer, name='faq_answer'),
]

ggaggoong/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import user.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user.views.home, name='home'),
    path('/', include('user.urls')),
    path('content/', include('content.urls')),
    path('faq/', include('faq.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from user import views
urlpatterns = [
    path('signup/', views.signup, name="signup"),
    # path('home/', views.home, name="home"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('user_update/', views.user_update, name="user_update"),
    path('host_signup/', views.host_signup, name="host_signup"),
    # path('host_login/', views.host_login, name="host_login"),
    path('host_update/', views.host_update, name="host_update"),
    path('mypage/', views.mypage, name='mypage'),
    path('host_mypage/', views.mypage, name='host_mypage'),
    # path('login_success/', views.login_success, name="login_success"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

class UserManager(BaseUserManager):    
   
   use_in_migrations = True    
   
   def create_user(self,username,mom_name,baby_name,baby_birth,baby_gender,address,phone, email, password):        
       
       if not email:            
           raise ValueError('must have user eamil')
       if not password:            
           raise ValueError('must have user password')

       user = self.model(  
           username=username,
           mom_name=mom_name,
           baby_name=baby_name,
           baby_birth=baby_birth,
           baby_gender=baby_gender,
           address=address,
           phone=phone,
           email=email,
       )        
       user.set_password(password)        
       user.save(using=self._db)        
       return user

   def create_superuser(self, email, password):        
   
       user = self.create_user(            
           email = email,
           password=password        
       )
       user.is_admin = True
       user.is_superuser = True
       user.save(using=self._db)
       return user 




class User(AbstractBaseUser, PermissionsMixin):
    """ User Model """
    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
    )
    username        = models.CharField(max_length=100, null=True)
    baby_name       = models.CharField(max_length=100)
    baby_gender     = models.CharField(max_length=80, choices=GENDER_CHOICES, null=True)
    baby_birth      = models.DateField(null=True)
    address         = models.CharField(max_length=200)
    mom_name        = models.CharField(max_length=200)
    phone           = models.CharField(max_length=100)
    email           = models.EmailField(max_length=100, unique=True, default='')
    password        = models.CharField(max_length=300)
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)
    is_active       = models.BooleanField(default=True)
    is_admin        = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    objects = UserManager()
    @property
    def is_staff(self):
       return self.is_admin


class Host(models.Model):
    user_id         = models.OneToOneField('User',on_delete=models.CASCADE, related_name="host_info")
    id_card1        = models.IntegerField()
    id_card2        = models.IntegerField()
    certificate_id  = models.IntegerField()
    crimelog        = models.ImageField(upload_to='ßimages/crimeLogImage',blank=True, null=True)
    crime_bool      = models.BooleanField(default=False)
    bank_img        = models.ImageField(upload_to='images/bankImage',blank=True, null=True)
    bank_num        = models.IntegerField()
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

user/views.py
from os import times
from django.shortcuts           import render
from django.contrib             import auth
# from ggaggoong.user.models      import Host
from user.models                import User, Host
from django.shortcuts           import render, redirect
from django.shortcuts           import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from datetime                   import datetime
from django.utils               import formats
from django.utils.dateformat    import DateFormat
from django.utils.formats       import get_format
import json, re
from django.http                import JsonResponse
from django.views               import View
from django.core.exceptions     import ValidationError
from django.contrib             import messages
import time, random, sys, traceback, logging, datetime
from content.models             import Contents, Contents_Detail, Reserve
from faq.models                 import FAQ, FAQ_Answer
from django.core.paginator import Paginator


# from .utils                     import validate_email, validate_password

def logout(request):
    if request.method == 'GET':
        auth.logout(request)
        redirect('home')
    return redirect('home')

def home(request):
    host_flag = False
    try:
        Host.objects.get(user_id=request.user.id)
        host_flag = True
    except:
        pass
    contents = Contents.objects.all().order_by("-created_at")
    count_per_page = 3
    pagenated_reserves = [contents[i * count_per_page:(i + 1) * count_per_page] for i in range((len(contents) + count_per_page - 1) // count_per_page)]
    return render(request, 'home.html', {"contents":contents, "host_flag":host_flag, "pagenated_reserves":pagenated_reserves})
# 회원가입
def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2'] and len(request.POST['password1']) >= 5:
            try:
                
                if not validate_email(request.POST['email']):
                    return JsonResponse({'MESSAGE':'INVALID_EMAIL_ADDRESS'}, status=404)

                if not validate_password(request.POST['password1']):
                    return JsonResponse({'MESSAGE':'INVALID_PASSWORD'}, status=404)

            except KeyError:
                return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=404)
            except ValidationError as e:
                return JsonResponse({'MESSAGE':e.message}, status=404)
            user = User.objects.create_user(
                    username=request.POST['mom_name'],
                    email=request.POST['email'],
                    mom_name=request.POST['mom_name'],
                    password=request.POST['password1'],
                    baby_name=request.POST['baby_name'],
                    baby_gender=request.POST['baby_gender'],
                    baby_birth=request.POST.get('baby_birth'),
                    phone=request.POST['phone_num'],
                    address=request.POST['address'],
                    
                    )
            if user is not None:
                auth.login(request, user)
                return redirect('home') #render(request, 'home.html', {'user':user})
    elif request.method == "GET" and request.user.id:
        return redirect('home')
    print("회원가입 안됨")
    return render(request, 'signup.html') 

@login_required
def host_signup(request):
    print(request.user.id)
    try:
        # host = Host()
        print('try')
        host = Host.objects.filter(user_id = request.user.id)
    except Host.DoesNotExist:
        print('except')
        host = None
    # if host is not None:
    #     print('if1')
    #     return render(request, 'host_signup.html', {'host' : Host.objects.filter(user_id = request.user.id)})
    if request.method == 'POST':
        print('if2')
        if request.user.id:
            print('if3')
            print(request.user.id)
            # user = User()
            host = Host()
            host.user_id = User.objects.get(id = request.user.id)
            host.id_card1 = request.POST["id_card1"]
            host.id_card2 = request.POST["id_card2"]            
            host.certificate_id = request.POST["certificate_id"]
            try: # request.FILES["crimelog"]:
                host.crimelog = request.FILES["crimelog"]
            except:
                pass
            host.crime_bool = request.POST["crime_bool"]
            try: # request.FILES["bank_img"]:
                host.bank_img = request.FILES["bank_img"]
            except:
                pass
            host.bank_num = request.POST["bank_num"]
            host.save()
            if host is not None:
                print('ssibal')
                # auth.login(request, user)
                return redirect('/user/home')
    print("회원가입 안됨")
    if request.method =='GET':
        if request.user.id is None:
            messages.warning(request, "회원가입 먼저 해주세요!")
            return redirect('signup')
        return render(request, 'host_signup.html')#redirect('signup')

def login(request):
    if request.method == 'GET':
        error_message = '로그인페이지입니다.'
        return render(request, 'login.html', {'error_message':error_message})
    elif request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = auth.authenticate(request, email=email, password=password)        
        if user is not None:
            auth.login(request, user)
            return redirect('home')#render(request, 'home.html', {'user':user})
        elif user is None:
            messages.warning(request, "회원정보가 없습니다 회원가입해주세요")
    error_message = '잘못된 요청입니다. 다시 로그인해주세요.'  
    return render(request, 'login.html', {'error_message':error_message})


# def host_login(request):
#     if request.method == 'GET':
#         if Host.objects.get(id=request.user.id) is not None:
#             return render(request, 'host_login.html')
            
#         elif Host.objects.get(id=request.user.id) is None:
#             error_message = '호스트 로그인페이지입니다.'
#             return render(request, 'host_signup.html',{'error_message':error_message})
#     error_message = '잘못된 요청입니다. 다시 로그인해주세요.'  
#     return render(request, 'login.html', {'error_message':error_message})


def user_update(request):
    id = request.user.id
    user = User.objects.get(id=id)
    if request.method == 'POST':
        user.username=request.POST['mom_name'],
        user.email=request.POST['email'],
        user.mom_name=request.POST['mom_name'],
        user.password=request.POST['password1'],
        user.baby_name=request.POST['baby_name'],
        user.baby_gender=request.POST['baby_gender'],
        user.baby_birth=request.POST.get('baby_birth'),
        user.phone=request.POST['phone_num'],
        user.address=request.POST['address']

        user.save()
        return redirect('home.html')
    elif request.method == "GET":
        return render(request, "user_update.html", {"user":user})


def host_update(request):
    user_id = request.user.id
    host = Host.objects.get(user_id = user_id)
    if request.method == 'POST':
        print(request.user.id)
        host.user_id = get_object_or_404(User, id=request.user.id)
        host.id_card1 = request.POST["id_card1"]
        host.id_card2 = request.POST["id_card2"]            
        host.certificate_id = request.POST["certificate_id"]
        try: # request.FILES["crimelog"]:
            host.crimelog = request.FILES["crimelog"]
        except:
            pass
        host.crime_bool = request.POST["crime_bool"]
        try: # request.FILES["bank_img"]:
            host.bank_img = request.FILES["bank_img"]
        except:
            pass
        host.bank_num = request.POST["bank_num"]
        host.save()
        if host is not None:
            # auth.login(request, user)
            return redirect('/user/home')
    elif request.method == "GET":
        return render(request, "host_signup.html", {"host":host})

def validate_email(email):
        return re.match('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', email) != None 

def validate_password(password):
        return len(password)>=5

def duplicate_email_check(email):
        return User.objects.filter(email=email).exists() 

def mypage(request):
    if request.method == "GET":
        # 호스트면 이거 보여주고 일반이면 안보여주고, 
        # to-do : 일반 사용자가 해당 컨텐츠에 지원하고 결제하는 부분까지 해야함
        try:
            # print(User.objects.get(id=request.user.id))
            # print(Contents.objects.filter(id=request.user.id))
            # print(FAQ.objects.filter(questioner=request.user.id))
            host_contents = Contents.objects.filter(host_id=request.user.id).order_by('-created_at')
            user = User.objects.get(id=request.user.id)
            faqs = FAQ.objects.filter(questioner=request.user.id).order_by('-created_at')
            reserves = Reserve.objects.filter(reserve_user=request.user.id).order_by('-created_at')
            
            count_per_page = 3
            pagenated_reserves = [reserves[i * count_per_page:(i+1) * count_per_page] for i in range((len(reserves) + count_per_page - 1) // count_per_page) ]

            try:
                host_pagenated_reserves = [host_contents[i * count_per_page:(i+1) * count_per_page] for i in range((len(host_contents) + count_per_page - 1) // count_per_page) ]
            except:
                host_pagenated_reserves = None
            # print('asdfadsjkfnasdkvnak')
            # print(host_pagenated_reserves)
            # print('asdfadsjkfnasdkvnak')


            total_reserve_price = 0
            total_reserve_price_flag = False
            remain_reserves = []
            canceled_reserves = []
            for reserve in reserves:
                total_reserve_price += reserve.content_id.price
                if reserve.content_id.content_date.isoformat() > datetime.datetime.now().isoformat():

user/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>Document</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'base.css' %}" type="text/css"/>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
<!--   font-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap" rel="stylesheet">





</head>

<body style="font-family: 'Gowun Dodum', sans-serif;">
<nav class="navbar navbar-expand-md navbar-dark sticky-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">까꿍</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="#aboutGgaggoong">까꿍이란</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#hotContents">인기 놀이</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#allContents">놀이 둘러보기</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mypage' %}">마이페이지</a>
          </li>
          {% endif %}
            
        </ul>
        {% if user.is_authenticated %}
        {% if host_flag %} 
        <a href="{% url 'Content:content_make' %}" style="padding-right:1rem"><button type="button" class="btn btn-light float-right">놀이 만들기</button></a>
        {% else %}
        <a href="{% url 'host_signup' %}" style="padding-right:1rem"><button type="button" class="btn btn-light float-right">호스트 가입하기</button></a>
        {% endif %}
        {% endif %}
        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" style="padding-right:1rem"><button type="button" class="btn btn-light float-right">로그아웃</button></a>
        <a href="{% url 'mypage' %}" style="padding-right:0.2rem"><button type="button" class=" btn btn-light float-right" name="action">마이페이지</button></a>
        {% else %}
        <a href="{% url 'signup' %}" style="padding-right:1rem"><button class="btn btn-light float-right" name="action">회원가입</button></a>
        <a href="{% url 'login' %}" style="padding-right:0.2rem"><button type="button" class="btn btn-light float-right">로그인</button></a>
        {% endif %}
        



      </div>
    </div>
  </nav>

    <head>
        <style>
            .bd-placeholder-img {
              font-size: 1.125rem;
              text-anchor: middle;
              -webkit-user-select: none;
              -moz-user-select: none;
              user-select: none;
            }
      
            @media (min-width: 768px) {
              .bd-placeholder-img-lg {
                font-size: 3.5rem;
              }
            }
            .comment{
              color: blue;
              margin-bottom: 1%;
            }
            .container_1{
              position: relative;
              padding: 10%;
              padding-top: 90px;
              padding-bottom: 1px;
              text-align: center;
            }
            .container_2{
              position: relative;
              padding: 2%;
              margin-top: 40px;
              padding-bottom: 50px;
              margin-left: 200px;
              margin-right: 200px;
              padding-left: 0px;
              padding-right: 0px;
            }
            .container{
              position: relative;
      
             }
      
          </style>
    </head>

    
    <!-- Custom styles for this template -->
    <link href="carousel.css" rel="stylesheet">
  </head>
  <body>


<div data-bs-spy="scroll" data-bs-target="#navbar-example2" data-bs-offset="0" class="scrollspy-example" tabindex="0">
{% load static %}
<div id="aboutGgaggoong" class="container_1 bg-image" style="background-image: url({% static 'baby_bck.jpeg' %}); background-position: center; background-repeat: no-repeat; background-size: cover;">
    <h2 >안녕하세요 까꿍입니다. <br>
        아이들에게는 새로운 놀이터를 <br>
        고객님께는 새로운 쉼터를 제공해드립니다. <br>
        까꿍을 통해 놀라운 경험들을 접해보세요.
    </h2>
    {% if user.is_authenticated %}
    <p class="comment"><br></p>
    {% else %}
    <p class="comment"> </p>
    {% endif %}
</div>

  
  <div id="hotContents" class="container marketing">
    <h1 style="padding-bottom: 2rem;"><div align="left">Hot Contents</div></h1> 
    <hr class="featurette-divider">
    <!-- Three columns of text below the carousel -->
    <div class="row" align="center">
      <div class="col-lg-4" style="display: block;">
        <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="{{ contents.0.title_img.url }}" role="img" aria-label="Placeholder: 140x140" align="center" />
        <h2 style="word-break: break-all;">{{ contents.0.title_name }}</h2>
        <p style="word-break: break-all;">{{ contents.0.sub_title_name }}</p>
        <p><a class="btn btn-secondary" href="{% url 'Content:content_detail' contents.0.id%}">더알아보기 &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4" style="display: block;">
        <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="{{ contents.1.title_img.url }}" role="img" aria-label="Placeholder: 140x140" align="center" />

        <h2 style="word-break: break-all;">{{ contents.1.title_name }}</h2>
        <p style="word-break: break-all;">{{ contents.1.sub_title_name }}</p>
        <p><a class="btn btn-secondary" href="{% url 'Content:content_detail' contents.1.id%}">더알아보기 &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4" style="display: block;">
        <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="{{ contents.2.title_img.url }}" role="img" aria-label="Placeholder: 140x140" align="center" />

        <h2 style="word-break: break-all;">{{ contents.2.title_name }}</h2>
        <p style="word-break: break-all;">{{ contents.2.sub_title_name }}</p>
        <p><a class="btn btn-secondary" href="{% url 'Content:content_detail' contents.2.id%}">더알아보기 &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">


    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->

    <div id="allContents" class="container marketing">
        <h1 style="padding-bottom: 2rem;"><div align="left">All Contents</div></h1>
        {% for content in contents %}
        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading">{{ content.title_name }} </h2>
                <span class="text-muted" >{{ content.content_date }}</span>
                <p class="lead" style="word-break: break-all;">{{ content.sub_title_name }}</p>
                <a href="{% url 'Content:content_detail' content.id %}" class="btn btn-primary">더 알아보기</a>
            </div>
            <div class="col-md-5">
                <img class="bd-placeholder-img" width="300" height="300" src="{{ content.title_img.url }}" />

            </div>
        </div>
        {% endfor %}
    </div>


</div>


    <script src="/docs/5.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

      
  </body>
</html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>



<footer class="bg-light text-center text-lg-start">
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase">(주)까꿍</h5>

        <p>
          대표 이지원 | 개인정보관리책임자 책임없음 | 사업자 등록번호 000 034034
            통신판매업 신고 2021-서울한남-0407 |
            서울특별시  송파구 신천동 29, 롯데월드타워 74층

        </p>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase">고객센터 / 기업제휴</h5>

        <p>
         운영시간 | 평일 00:01~23:59
     카톡 | 카카오톡 친구 맘마미아
     전화 | 1541 7979
     메일 | jagosipda@mama.kr
     블로그 | blog.naver.com/mama

        </p>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

</footer>




</html>



<style>
.container{
    position: relative;
    padding: 10%;
    text-align: center;
}
.login_logo{
    margin: 50% 0 10% 0;
}
.comment{
    color: white;
    margin-bottom: 40%;
}
.button{
    text-decoration: none;
    color: rgb(255,120,137);
    font-size: 0.9rem;
    background-color: white;
    border-radius: 0.7rem;
    /* width: 50%; */
    height: 6%;
    text-align: center;
    letter-spacing: .5px;
    -webkit-transition: background-color .2s ease-out;
    transition: background-color .2s ease-out;
    cursor: pointer;
}

</style>

user/templates/host_login.html
{% extends "base.html" %}

host log in

user/templates/host_mypage.html
{% extends "base.html" %}

user/templates/login_success.html
{% extends "base.html" %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
</head>
<body style="background-color: rgb(255,120,137);">
    <div class="container">
        <img class="login_logo" src="/static/logo_white.png" alt="chachacha">
        <div>
            <p class="comment">차차차 회원이 되신 것을 <br>
                {% user %} 님 축하드립니다.
            </p>
        </div>
        <div>
            <a href="{% url 'login' %}"><button class="button waves-effect waves-light" name="action">로그인</button></a>
            
        </div>
    </div>
    
</body>
</html>


<style>
.container{
    position: relative;
    padding: 10%;
    text-align: center;
}
.login_logo{
    margin: 50% 0 10% 0;
}
.comment{
    color: white;
    margin-bottom: 40%;
}
.button{
    text-decoration: none;
    color: rgb(255,120,137);
    font-size: 0.9rem;
    background-color: white;
    border-radius: 0.7rem;
    width: 50%;
    height: 6%;
    text-align: center;
    letter-spacing: .5px;
    -webkit-transition: background-color .2s ease-out;
    transition: background-color .2s ease-out;
    cursor: pointer;
}

</style>